kvExtract: ENH: UI: Consistency: Also support --input-files FILE [...] ;
This is useful with shell globbing.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/kvExtract b/bin/kvExtract
--- a/bin/kvExtract
+++ b/bin/kvExtract
@@ -1,11 +1,13 @@
 #!/bin/bash
 
+: ${KVEXTRACT_INPUTFILES_END=;}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-F|--field-separator INPUT-SEPARATOR] [-s|--output-separator OUTPUT-SEPARATOR] [--duplicate-key first|last|error|abort] [--] KEY1 [KEY2 ...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [-i ...] ... [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -i|--input FILE [-i ...]|--input-files FILE [...] ${KVEXTRACT_INPUTFILES_END} [-?|-h|--help]"
 }
 printUsage()
 {
@@ -34,18 +36,39 @@ HELPDESCRIPTION
 				are not extracted at all. (This is the default.)
     --duplicate-key abort	Duplicate keys in the input cause the entire
 				extract to abort.
+    --input|-i FILE	Read from FILE(s) instead of standard input.
+    --input-files FILE [...] ${KVEXTRACT_INPUTFILES_END}
+			Read from the following FILE(s) i.e. all following
+			arguments until an argument consisting of '${KVEXTRACT_INPUTFILES_END}'
+			is encountered instead of standard input.
 HELPTEXT
 }
 
 typeset -a fsArgs=()
-typeset -a awkArgs=()
+typeset -a inputFilespecs=()
 outputSeparator=$'\n'
 onDuplicateKey=error
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--input|-i)	shift; awkArgs+=("$1"); shift;;
+	--input|-i)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$KVEXTRACT_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${KVEXTRACT_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
 	--field-separator|-F)
 			shift; fsArgs=(-F "$1"); shift;;
 	--output-separator|-s)
@@ -120,4 +143,4 @@ END {
     }
     exit status
 }
-' "${awkArgs[@]}"
+' "${inputFilespecs[@]}"
